Changelog for 0.5.0
redhat-developer/vscode-microprofile pull request #101
Opened 2022-07-14 19:49 UTC by rgrunber

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

2022-07-15 14:28 UTC, datho7561 requested changes

2022-07-15 14:28 UTC, datho7561 commented on CHANGELOG.md
> +### Enhancements
Make sure to include any of the noteworthy enhancements or bug fixes from the new release of lsp4mp

2022-07-15 14:58 UTC, datho7561 commented on CHANGELOG.md
> +### Enhancements
My bad, looks like you've got all of them

2022-07-15 15:49 UTC, datho7561 approved these changes
Looks good. Thanks, Roland!

2022-07-19 14:11 UTC, rgrunber commented
Let's revisit the `other` changes and re-categorize them.

2022-07-19 15:31 UTC, datho7561 commented on CHANGELOG.md
> + * Add DCO information to `CONTRIBUTING.md`. See [#99](https://github.com/redhat-developer/vscode-microprofile/issues/99).
documentation maybe

2022-07-19 15:31 UTC, datho7561 commented on CHANGELOG.md
> + * Remove ejs dependency. See [#97](https://github.com/redhat-developer/vscode-microprofile/pull/97).
build maybe

2022-07-19 15:31 UTC, datho7561 commented on CHANGELOG.md
> + * Improved MicroProfile property value expression diagnostic message. See [eclipse/lsp4mp#242](https://github.com/eclipse/lsp4mp/pull/242).
enhancement

2022-07-22 18:57 UTC, datho7561 commented on CHANGELOG.md
> +## [0.5.0](https://github.com/redhat-developer/vscode-microprofile/milestone/5?closed=1) (July 28, 2022)
Update the date to the 25th

2022-07-25 14:58 UTC, merged