Changelog for 0.6.0
redhat-developer/vscode-microprofile pull request #130
Opened 2022-11-23 20:05 UTC by rgrunber

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

2022-11-23 20:31 UTC, datho7561 requested changes

2022-11-23 20:31 UTC, datho7561 commented on CHANGELOG.md
> +### Enhancements
I just merged the "activation trigger should be more selective" PR, I think that should be listed here

2022-11-23 20:31 UTC, datho7561 commented on CHANGELOG.md
> + * Display property when hovering over a key that isn't defined in the application. See [eclipse/lsp4mp#285](https://github.com/eclipse/lsp4mp/issues/285).
Display property value....

2022-11-23 20:31 UTC, datho7561 commented on CHANGELOG.md
> +## [0.6.0](https://github.com/redhat-developer/vscode-microprofile/milestone/6?closed=1) (November 29, 2022)
Make sure to include any unique fixes from https://github.com/redhat-developer/vscode-microprofile/milestone/6?closed=1. I think there are a few there we should add

2022-11-23 21:40 UTC, rgrunber commented on CHANGELOG.md
> +## [0.6.0](https://github.com/redhat-developer/vscode-microprofile/milestone/6?closed=1) (November 29, 2022)
I wasn't really sure about including this since, there isn't really supposed to be anything that is visible for the user.

2022-11-23 21:49 UTC, datho7561 commented on CHANGELOG.md
> +## [0.6.0](https://github.com/redhat-developer/vscode-microprofile/milestone/6?closed=1) (November 29, 2022)
Okay. That makes sense!

2022-11-23 21:50 UTC, datho7561 approved these changes
Looks good. Thanks Roland!

2022-11-29 11:11 UTC, fbricon commented
please add https://github.com/redhat-developer/vscode-microprofile/pull/131

2022-12-01 15:37 UTC, merged