Initiate YAML schema registration only when YAML file is open or created
redhat-developer/vscode-microprofile pull request #163
Opened 2023-07-17 20:58 UTC by hopehadfield

Fixes #160

2023-07-17 21:10 UTC, angelozerr commented on src/extension.ts
> +    if (yamlRegistered == false && (e.fileName.includes("application.yaml") || e.fileName.includes("application.yml")
To avoid duplicate code, I suggest that you create 2 functions:

 * `isYamlConfigSource(fileName : string) : boolean` which have the file name in parameter and check if the file is  the application.yaml, etc
 * `registerYamlSchemaSupportIfNeeded(fileName: string)` which register the yaml schema support if the fileName matches isYamlConfigSource. This method can be called in onDidOpenTextDocument and onDidCreateFiles

2023-07-17 22:09 UTC, rgrunber commented on src/extension.ts
> +    if (yamlRegistered == false && (e.fileName.includes("application.yaml") || e.fileName.includes("application.yml")
Also maybe the different files could be combined into a regular expression. Also I think includes does a substring search. Is that we want ? Seems to me we should do an exact match.

2023-07-18 05:42 UTC, angelozerr commented on src/extension.ts
> +    if (yamlRegistered == false && (e.fileName.includes("application.yaml") || e.fileName.includes("application.yml")
The application.yaml can incluse the profile name in microprofile so we dont do the exact match

2023-07-18 13:32 UTC, angelozerr commented on src/extension.ts
> +    if (yamlRegistered == false && (e.fileName.includes("application.yaml") || e.fileName.includes("application.yml")
See the spec at https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#_on_config_source_level

In other words, the pattern is `application-*.yaml`  (ex: `application-dev.yaml`). 

@hopehadfield I think your current code doesn't support this file name pattern. Once it will be supported could you add please as comment a link to https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#_on_config_source_level
 to explain why you check `application-*.yaml`

2023-07-18 17:34 UTC, angelozerr commented
I have not tested but the code looks great, congrats @hopehadfield

2023-07-19 18:55 UTC, rgrunber requested changes
I haven't run this yet but it does look mostly fine.

2023-07-19 18:55 UTC, rgrunber commented on src/extension.ts
> +  let yamlRegistered = false;
Could we just use `yamlSchemaCache` to also represent if registration happened ? That way we wouldn't need `yamlRegistered` at all.

So `if (yamlOpen())` is `true` and `yamlSchemaCache` is `null`, we register. Otherwise, we don't

I think this would also simplify `registerYamlSchemaSupportIfNeeded(..)` to the point that you could check the file directly in the callback and just call `registerYamlSchemaSupport()` rather than having the extra helper method to check if it's needed.

According to https://dev.to/typescripttv/what-is-the-difference-between-null-and-undefined-5h76 we should set to `null` as you did but in most of the codebase I see use using `undefined`.

2023-07-19 20:51 UTC, rgrunber commented
@angelozerr , I think there's a problem here. Without this change, If I open a quarkus project, I can see the properties show up in the `application.yaml` (renamed from `application.properties`) :

![image](https://github.com/redhat-developer/vscode-microprofile/assets/1417342/40a20510-5040-44d7-b864-2782e67b39df)

With this change, it no longer shows the propeties/namespaces (eg. config_ordinal, mp, quarkus, greeting)

2023-07-19 21:09 UTC, fbricon commented
@rgrunber I think you need some microprofile yaml config dependency in the project classpath

2023-07-19 21:21 UTC, rgrunber commented
I think it has to do with whether the yaml language server starts before or after the call to https://github.com/redhat-developer/vscode-microprofile/blob/c15b06b4c3c9e934384be586140c64342d11724e/src/yaml/YamlSchema.ts#L122 . Currently we always start the YAML language server. This change makes it so that while the YAML language server only starts if a YAML file is opened. Even though I can clearly see the registered callbacks being triggered, the completions aren't showing up.

I was able to fix it by simply expanding the activation condition in this PR for `yamlOpen()` to also include the case when an `application.yaml` file is anywhere in the workspace.

2023-07-19 23:46 UTC, rgrunber commented
Ok, I think I found the other problem. It starts here : https://github.com/redhat-developer/vscode-microprofile/blob/c15b06b4c3c9e934384be586140c64342d11724e/src/extension.ts#L68-L69

We start the MicroProfile language server, and once done, we pass the language client reference to the yaml cache, so we can make the necessary queries for properties. However if we don't register YAML support, then the cache is undefined, and this happens when no YAML file is opened.

Possible solutions are :
1) Just add some code to `yamlOpen()` (also method should be renamed) that detects if any `application.yaml` (or the other patterns) are in the workspace so it activates in more cases. However this won't work when a user creates a new file.
2) Decouple the yaml cache from the activation of the yaml extension. It's just an object. I don't see a reason why we need to define it there. We could always define it on extension activation.

2023-07-24 23:16 UTC, rgrunber approved these changes

2023-07-24 23:40 UTC, merged