Add CHANGELOG 0.1.0
redhat-developer/vscode-microprofile pull request #19
Opened 2020-09-11 13:10 UTC by angelozerr

Add CHANGELOG 0.1.0

Signed-off-by: azerr <azerr@redhat.com>

2020-09-18 16:18 UTC, fbricon requested changes

2020-09-18 16:18 UTC, fbricon commented on CHANGELOG.md
> + * Initial contribution. See [#1](https://github.com/redhat-developer/vscode-microprofile/pull/1).
that we can remove

2020-09-21 06:24 UTC, angelozerr commented on CHANGELOG.md
> + * Initial contribution. See [#1](https://github.com/redhat-developer/vscode-microprofile/pull/1).
removed.

2020-09-21 07:29 UTC, fbricon approved these changes

2020-09-21 07:29 UTC, merged