Update name to Tools for MicroProfile
redhat-developer/vscode-microprofile pull request #24
Opened 2020-09-23 21:08 UTC by rzgry

Fixes #23 

Signed-off-by: Ryan Zegray <ryan.zegray@ibm.com>

2020-09-23 21:13 UTC, datho7561 approved these changes

2020-09-23 21:27 UTC, fbricon commented on README.md
> +MicroProfile(R) and the MicroProfile logo are trademarks of the Eclipse Foundation
use ®

2020-09-23 21:28 UTC, fbricon commented on README.md
> +By default Tools for MicroProfile provides:
By default,

2020-09-23 21:36 UTC, fbricon commented on CHANGELOG.md
> +* Update name to Tools for MicroProfile. See [#23](https://github.com/redhat-developer/vscode-microprofile/issues/23)
"Tools for MicroProfile"

2020-09-23 21:39 UTC, fbricon requested changes

2020-09-23 21:39 UTC, fbricon commented on README.md
This Visual Studio Code extension provides support for the development of [MicroProfile®](https://microprofile.io/)-based applications, via:

2020-09-24 08:56 UTC, merged

2020-09-24 08:57 UTC, fbricon commented
Thanks @rzgry