Switched TSLint to ESLint
redhat-developer/vscode-microprofile pull request #54
Opened 2021-06-08 14:57 UTC by AlexXuChen

Replaced TSLint and its dependencies to ESLint and its dependencies as linter for `*.ts` files in `src`.

Closes #53

Signed off by: Alexander Chen <alchen@redhat.com>

2021-06-08 15:03 UTC, AlexXuChen commented
There will be linting errors on the Travis-CI atm, since I just changed the linter, will fix now

2021-06-08 15:48 UTC, datho7561 requested changes

2021-06-08 15:48 UTC, datho7561 commented on .vscode/tasks.json
> +        "$eslint-webpack-watch"
I think you can remove this line. This line sets up a background task that scans the webpack output for eslint errors, and translates those errors into error underlines in the editor. We don't integrate eslint with webpack at the moment, so I don't think this will do anything. It looks like we could integrate eslint with webpack with this tool, which might be cool: https://webpack.js.org/plugins/eslint-webpack-plugin/

Take a look into setting up a [VS Code task](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection) for eslint.

2021-06-09 19:28 UTC, datho7561 requested changes

2021-06-09 19:28 UTC, datho7561 commented on src/definitions/commands.ts
> + * Copyright 2019 Red Hat, Inc. and others.
Since this is a new file, I think you should update the copyright header year

2021-06-09 19:28 UTC, datho7561 commented on src/definitions/microProfileLS.ts
> + * Copyright 2019 Red Hat, Inc. and others.
copyright header year

2021-06-09 19:28 UTC, datho7561 commented on src/definitions/microProfileLS.ts
> +/**
I think this file could use a more descriptive name, maybe something like `microProfileLSRequestNames.ts`

2021-06-09 19:28 UTC, datho7561 commented on src/languageServer/javaServerStarter.ts
> +  import * as os from 'os';
Remove this indent

2021-06-09 19:59 UTC, datho7561 approved these changes
LGTM

2021-06-09 19:59 UTC, merged