added java features documentation and examples for MicroProfile
redhat-developer/vscode-microprofile pull request #79
Opened 2021-11-08 17:01 UTC by AlexXuChen

Added java features documentation and examples for MicroProfile.

Closes #64 

Signed-off-by: Alexander Chen <alchen@redhat.com>

2021-11-08 20:13 UTC, angelozerr commented on docs/JavaFeatures.md
> +![MP Java Completion](./res/MPJavaCompletion.gif)
The demo show completion for annotation which is managed by vscode-java (JDT LS), so without vscode-microprofile you will have completion support too.

The completion support for microprofile is for fault tolerant with fallback method. Please show this demo.

2021-11-08 20:15 UTC, angelozerr commented on docs/JavaFeatures.md
> +![MP Java Hover](./res/MPJavaHover.gif)
Same comment than below,this feature comes from vscode-java. You should see demo with hover in ConfigProperty/@name

2021-11-09 12:56 UTC, angelozerr commented on docs/JavaFeatures.md
> +
For the demo, I wouldlike to avoid showing snippet in action because perhaps we will remove it. It should be nice that you show in action the completion for fallbackmethod attribute value. You could use the sample https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#_specify_the_fallbackmethod

 ```java
​@Retry(maxRetries = 2)
   ​@Fallback(fallbackMethod= "fallbackForServiceB")
   ​public String serviceB() {
       ​counterForInvokingServiceB++;
      ​return nameService();
   ​}

   ​private String fallbackForServiceB() {
   }
}
```

Completion on `|` for:

​@Fallback(fallbackMethod= "|")

should sow `fallbackForServiceB`

2021-11-09 14:17 UTC, AlexXuChen commented on docs/JavaFeatures.md
> +
Is there a setting to enable this completion? I'm not seeing the completion behaviour.

2021-11-09 16:43 UTC, angelozerr requested changes

2021-11-09 16:45 UTC, angelozerr commented
Definition support is too supported (Hyperlink). You can do 2 demos:

 * one with fallback method to jump from fallbackMethod to the declared method (java -> java)
 * one with Ctrl+Click on value of ConfigProperty/@name to jump to the propertiesfile (java -> properties)

2021-11-16 17:37 UTC, merged

2021-11-16 17:38 UTC, angelozerr commented
Thanks @AlexXuChen !