Added textmate grammar support for property expressions
redhat-developer/vscode-microprofile pull request #95
Opened 2022-06-08 17:51 UTC by JessicaJHee

![image](https://user-images.githubusercontent.com/73968480/172683945-bbbbe579-3e20-4b3e-94ab-97bbbd9e8402.png)

Fixes redhat-developer/vscode-quarkus#272

Signed-off-by: Jessica He <jhe@redhat.com>

2022-06-08 18:34 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "begin": "(from)\\s+([a-zA-Z]+)",
We can use `from` in an expression? I don't see that in https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/property-expressions.asciidoc#property-expressions

2022-06-08 18:53 UTC, JessicaJHee commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "begin": "(from)\\s+([a-zA-Z]+)",
Yeah I wasn't too sure but the poster of the original issue had it in the screenshot so I included it. I guess it would be better to remove it since there is nothing on it in the documentation?

2022-06-09 07:52 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "include": "#from"
Please remove this rule.

2022-06-09 07:53 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +    "from":{
Please remove this rule.

2022-06-09 07:55 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "comment": "Matching for expression",
"comment": "Matching for expression. Ex : ${expression:value}"

2022-06-09 08:21 UTC, angelozerr requested changes

2022-06-09 08:21 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.character.java-properties"
I would rename with 

`support.constant.java-properties`

like :

* vscode does for handlebars : https://github.com/microsoft/vscode/blob/54ae4d8ccbf4574889c24b086079a745b3debf96/extensions/handlebars/syntaxes/Handlebars.tmLanguage.json#L377
* we do for qute : https://github.com/redhat-developer/vscode-quarkus/blob/251e12154c1b824e55dd04667e53b897e10e1452/language-support/qute/qute.tmLanguage.json#L133

2022-06-09 08:21 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.character.java-properties"
`support.constant.java-properties`

2022-06-09 08:21 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "begin": "(from)\\s+([a-zA-Z]+)",
The sample with `from` must not colorized it is just a plain strings. I suggest that you read https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/property-expressions.asciidoc#property-expressions :

`An expression string is a mix of plain strings and expression segments, which are wrapped by the sequence ${ …​ }`

2022-06-09 08:45 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "include": "#noSequence"
Why you need this rule? The property expression are available only in property value, so I think you can remove this rule.  Or perhaps I miss something?

2022-06-09 09:22 UTC, angelozerr commented
At first @JessicaJHee could you move the rule for coments, property key and property value in a repository to have the root patterns like this:

```json
"patterns": [
       {
          "include": "#comments"
        },
        {
          "include": "#property-key"
        },
        {
          "include": "#property-value"
        }
]
```

I think it should be more readable.

2022-06-09 15:20 UTC, JessicaJHee commented
![image](https://user-images.githubusercontent.com/73968480/172882536-80a11603-3115-454c-bcb1-d6b6f81a6199.png)

After the changes this is what it looks like, the links / strings that are not inside ${...} are now plain with the numbers highlighted.

2022-06-10 11:41 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +      "begin": "(?<!\\/)(\\$\\{)([a-zA-z.]+)(:)?([a-zA-z0-9]+)?",
I think begin should be just the start expression (just `${`). It will give the capability to highlight with color `${}`. So I suggest that you remove `([a-zA-z.]+)(:)?([a-zA-z0-9]+)?` and yoiu add this match the "pattern" (before the include of #expression).

2022-06-10 15:03 UTC, JessicaJHee commented
![image](https://user-images.githubusercontent.com/73968480/173094398-7066cb7a-76a6-473f-bfba-600f7d3518ed.png)

The `${}` is now a light yellow colour (`support.constant.handlebars.java-properties`)

2022-06-10 15:45 UTC, fbricon commented
@JessicaJHee in your screenshot, the variables inside urls are not colored like the others

2022-06-10 16:11 UTC, JessicaJHee commented
![image](https://user-images.githubusercontent.com/73968480/173107536-8eb8ec11-60e8-4311-be51-8beb38ca9bb3.png)

2022-06-10 17:31 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "support.constant.handlebars.java-properties"
It is annoying to use handlebars because it means that there is some dependency to the handlebar TextMate.

I tried `support.function.java-properties` where function is standard, and it seems it works. I have no explanation why `support.constant.java-properties` doesn't work?

I suggest that you change with `support.function.java-properties`

2022-06-10 17:32 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.numeric.default.value.java-properties"
Default value is not only numeric, we need to find a better name for that by keeping an another color.

2022-06-10 17:40 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.numeric.default.value.java-properties"
More default value is not a constant we should try to use variable instead of constants by having à different color.  I dont know if it is possible.

2022-06-10 17:42 UTC, angelozerr commented
@JessicaJHee your last screenshot looks very promising. If we could keep the sale color by fixing my 2 comments it should be really nice.

2022-06-10 18:16 UTC, JessicaJHee commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "support.constant.handlebars.java-properties"
Great I will change to `support.function.java-properties`.

I believe it's because support.constant is not defined in the default dark + theme in that yellow colour. 

https://github.com/microsoft/vscode/blob/a3d5ada781417d7619e30e3da4a9f6526a269d9c/extensions/theme-defaults/themes/dark_plus.json#L11

2022-06-10 18:23 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "support.constant.handlebars.java-properties"
Nice catch!

2022-06-10 19:08 UTC, JessicaJHee commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.numeric.default.value.java-properties"
I'm not sure if I understand, do you suggest a new colour or try to keep the old one? It seems like the old colour is mainly used for numeric values but is also used for `variable.other.enummember`.

Otherwise, the colour of names for variables are very similar to others. So if we want to change to another colour we can also do: 
![image](https://user-images.githubusercontent.com/73968480/173132943-ee5e1794-680b-40be-a008-aa154bf98a42.png)
Where the green (ex:greeting.name) is `entity.name.type.java-properties` and the value portion is `variable.other.value.java-properties`

2022-06-14 08:40 UTC, angelozerr commented on language-support/properties-support/java-properties.tmLanguage.json
> +          "name": "constant.numeric.default.value.java-properties"
I mean don't use `numeric` please, because default value is not only a numeric and try to have a different color for default value. Your screenshot looks good, so please apply your suggestion.

2022-06-14 13:42 UTC, JessicaJHee commented
Appearance after change: 

![image](https://user-images.githubusercontent.com/73968480/173591684-5ef9550e-c6b2-470e-b9ea-4bdae7699eec.png)

2022-06-14 14:26 UTC, merged

2022-06-14 14:26 UTC, angelozerr commented
Great job @JessicaJHee !